server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mySql://localhost:3306/order-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wiley

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect




eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:password@localhost:8761/eureka






