server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mySql://localhost:3306/order-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wiley

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#      ddl-auto: update