#server:
#  port: 9090
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http:localhost:8761/eureka
#
#logging:
#  level:
#    root: info
#
#
#
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#        - uri: lb://product-service
#        - predicates:
#            - Path=/api/product
